"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Copy, ExternalLink, MessageCircle, RefreshCw, ShieldAlert, XCircle } from "lucide-react";
import { authedFetch } from "@/lib/api/authedFetch";

type AnyRow = Record<string, any>;
function s(v:unknown){return String(v??"").trim();}

export default function TrainerControleAdminPage(){
 const params=useParams<{matchmakingId?:string;matchmakingid?:string}>();
 const matchmakingId=s(params?.matchmakingId??params?.matchmakingid);
 const [data,setData]=useState<AnyRow|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{ if(!matchmakingId)return; setLoading(true); try{const r=await authedFetch(`/api/matchmaker/trainercontrole?matchmakingId=${encodeURIComponent(matchmakingId)}`); const j=await r.json().catch(()=>({})); if(!r.ok)throw new Error(j.error||"Laden mislukt"); setData(j);}catch(e:any){setMsg(e.message||"Laden mislukt");}finally{setLoading(false);}},[matchmakingId]);
 useEffect(()=>{load();},[load]);
 const createLink=async(gym:AnyRow)=>{setBusy(gym.key);setMsg("");try{const r=await authedFetch("/api/matchmaker/trainercontrole",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({matchmakingId,sportschool:gym.naam})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Link maken mislukt");await load();}catch(e:any){setMsg(e.message||"Link maken mislukt");}finally{setBusy("");}};
 const linkUrl=(g:AnyRow)=>g?.link?.token?`${window.location.origin}/trainercontrole/${g.link.token}`:"";
 const copy=async(g:AnyRow)=>{const u=linkUrl(g);if(!u)return;await navigator.clipboard.writeText(u);setMsg(`Link van ${g.naam} gekopieerd.`)};
 const whatsapp=(g:AnyRow)=>{const u=linkUrl(g);if(!u)return;const text=`Beste trainer van ${g.naam},\n\nVia onderstaande link staan alle partijen van jouw sportschool klaar voor controle. Reageer per partij met Akkoord, Afwijzen of Bespreken. Als dispensatie nodig is, staat de reden erbij en is nadrukkelijke toestemming vereist.\n\n${u}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");};
 const totals=useMemo(()=>{const gyms=data?.gyms??[];return gyms.reduce((a:any,g:any)=>{a.gyms++;a.bouts+=g.bouts?.length||0;a.open+=g.counts?.open||0;a.akkoord+=g.counts?.akkoord||0;a.afgewezen+=g.counts?.afgewezen||0;a.bespreken+=g.counts?.bespreken||0;return a;},{gyms:0,bouts:0,open:0,akkoord:0,afgewezen:0,bespreken:0});},[data]);
 return <main className="tc-page">
  <style jsx global>{`
   body{background:#111;color:#f7f7f7}.tc-page{min-height:100vh;padding:18px;font-family:Inter,Arial,sans-serif}.tc-shell{max-width:1380px;margin:auto}.tc-head{display:flex;align-items:center;justify-content:space-between;gap:12px;background:linear-gradient(180deg,#292929,#1c1c1c);border:1px solid #555;padding:12px 14px}.tc-title{display:flex;align-items:center;gap:12px}.tc-title a,.tc-btn{border:1px solid #666;background:#242424;color:white;padding:9px 11px;text-decoration:none;display:inline-flex;align-items:center;gap:7px;font-weight:800;cursor:pointer}.tc-btn.orange{background:#ff4d00;border-color:#ff4d00}.tc-btn.whatsapp{background:#202c23}.tc-btn:disabled{opacity:.45;cursor:not-allowed}.tc-kicker{color:#ff6a2b;font-size:11px;font-weight:900;letter-spacing:.12em}.tc-head h1{font-size:22px;margin:2px 0 0}.tc-sub{color:#bbb;margin:5px 0 0;font-size:13px}.tc-stats{display:grid;grid-template-columns:repeat(5,minmax(110px,1fr));gap:8px;margin:12px 0}.tc-stat{background:#1b1b1b;border:1px solid #444;padding:10px}.tc-stat b{font-size:22px;display:block}.tc-stat span{font-size:11px;color:#aaa;text-transform:uppercase;font-weight:800}.tc-msg{margin:10px 0;padding:9px 11px;border-left:4px solid #ff4d00;background:#211b19}.tc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.tc-card{background:#1a1a1a;border:1px solid #484848}.tc-card-top{display:flex;justify-content:space-between;gap:10px;padding:12px 13px;border-bottom:1px solid #3a3a3a;background:#222}.tc-card h2{font-size:18px;margin:0}.tc-badges{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.tc-badge{font-size:11px;font-weight:900;padding:4px 7px;border:1px solid #555}.tc-badge.ok{border-color:#467a52}.tc-badge.bad{border-color:#9b3a35}.tc-badge.warn{border-color:#a77628}.tc-body{padding:12px 13px}.tc-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.tc-link{background:#101010;border:1px solid #3e3e3e;padding:8px;font-family:monospace;font-size:11px;color:#ccc;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:9px}.tc-opened{font-size:11px;color:#aaa;margin-top:7px}.tc-empty{padding:30px;text-align:center;color:#aaa;border:1px dashed #555}@media(max-width:900px){.tc-grid{grid-template-columns:1fr}.tc-stats{grid-template-columns:repeat(2,1fr)}}
  `}</style>
  <div className="tc-shell">
   <header className="tc-head"><div className="tc-title"><Link href={`/dashboard/matchmaker/matchmaking/${matchmakingId}/match`}><ArrowLeft size={17}/></Link><div><div className="tc-kicker">TRAINERCONTROLE</div><h1>{data?.event?.title||"Matchmaking"}</h1><p className="tc-sub">Per sportschool één beveiligde pagina met alleen de eigen partijen en alle bijzonderheden.</p></div></div><button className="tc-btn" onClick={load} disabled={loading}><RefreshCw size={16}/>Vernieuwen</button></header>
   <section className="tc-stats"><div className="tc-stat"><b>{totals.gyms}</b><span>Sportscholen</span></div><div className="tc-stat"><b>{totals.open}</b><span>Nog open</span></div><div className="tc-stat"><b>{totals.akkoord}</b><span>Akkoord</span></div><div className="tc-stat"><b>{totals.bespreken}</b><span>Bespreken</span></div><div className="tc-stat"><b>{totals.afgewezen}</b><span>Afgewezen</span></div></section>
   {msg&&<div className="tc-msg">{msg}</div>}
   {loading?<div className="tc-empty">Trainercontrole wordt geladen…</div>:!(data?.gyms?.length)?<div className="tc-empty">Geen sportscholen met partijen gevonden.</div>:<div className="tc-grid">{data.gyms.map((g:AnyRow)=><article className="tc-card" key={g.key}><div className="tc-card-top"><div><h2>{g.naam}</h2><div className="tc-badges"><span className="tc-badge">{g.bouts.length} partij{g.bouts.length===1?"":"en"}</span>{g.keurmerkOk===true?<span className="tc-badge ok">Keurmerk geldig</span>:g.keurmerkOk===false?<span className="tc-badge bad">Geen geldig keurmerk</span>:<span className="tc-badge warn">Keurmerk onbekend</span>}</div></div>{g.counts?.open===0&&g.bouts.length>0?<CheckCircle2 size={26}/>:g.counts?.afgewezen>0?<XCircle size={26}/>:<ShieldAlert size={26}/>}</div><div className="tc-body">{g.keurmerkReden&&<div className="tc-sub">{g.keurmerkReden}</div>}<div className="tc-badges"><span className="tc-badge ok">{g.counts?.akkoord||0} akkoord</span><span className="tc-badge warn">{g.counts?.bespreken||0} bespreken</span><span className="tc-badge bad">{g.counts?.afgewezen||0} afgewezen</span><span className="tc-badge">{g.counts?.open||0} open</span></div>{g.link?<><div className="tc-link">{linkUrl(g)}</div><div className="tc-actions"><button className="tc-btn" onClick={()=>copy(g)}><Copy size={15}/>Kopieer</button><button className="tc-btn whatsapp" onClick={()=>whatsapp(g)}><MessageCircle size={15}/>WhatsApp</button><button className="tc-btn" onClick={()=>window.open(linkUrl(g),"_blank","noopener,noreferrer")}><ExternalLink size={15}/>Open</button></div>{g.link.openedAt&&<div className="tc-opened">Trainer heeft de pagina geopend.</div>}</>:<button className="tc-btn orange" disabled={busy===g.key} onClick={()=>createLink(g)}>{busy===g.key?"Link maken…":"Maak trainerlink"}</button>}</div></article>)}</div>}
  </div>
 </main>
}
