import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import ExcelJS from "exceljs";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import fs from "node:fs";
import path from "node:path";
import { requireAdmin } from "@/app/api/_utils/authz";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Row = Record<string, any>;
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
function s(v: unknown) { return String(v ?? "").trim(); }
function first(...values: unknown[]) { for (const v of values) { const out = s(v); if (out) return out; } return ""; }
function d(v: unknown) { const raw = s(v); if (!raw) return null; const out = new Date(raw); return Number.isNaN(out.getTime()) ? null : out; }
function fmtDate(v: unknown) { const x = d(v); return x ? new Intl.DateTimeFormat("nl-NL", { day: "2-digit", month: "2-digit", year: "numeric" }).format(x) : (s(v) || "-"); }
function fmtDateTime(v: unknown) { const x = d(v); return x ? new Intl.DateTimeFormat("nl-NL", { day: "2-digit", month: "2-digit", year: "numeric", hour:"2-digit", minute:"2-digit" }).format(x) : (s(v) || "-"); }
function eventNaam(r: Row) { return first(r.event_naam, r.evenement_naam, r.raw?.matchmaking?.naam, r.raw?.event?.naam, r.raw?.evenement_naam, "-"); }
function eventDatum(r: Row) { return first(r.event_datum, r.evenement_datum, r.raw?.matchmaking?.datum, r.raw?.event?.datum); }
function naam(r: Row) { return first(r.naam, r.naam_input, r.fp_naam, [r.voornaam, r.achternaam].map(s).filter(Boolean).join(" "), r.raw?.fighter_context?.naam, "Onbekend"); }
function sportschool(r: Row) { return first(r.sportschool, r.gym, r.gym_input, r.fp_gym, r.raw?.aanmelding?.gym, r.raw?.fighter_context?.gym_input, "-"); }
function reden(r: Row) { return first(r.reden, r.opmerking, r.beoordelings_opmerking, r.raw?.afmelding?.reden, "-"); }
function bondteam(r: Row) { return first(r.bondteam, r.raw?.matchmaking?.bondteam, r.raw?.aanmelding?.bondteam, "-"); }
function afgemeldAt(r: Row) { return first(r.afgemeld_at, r.raw?.afmelding?.afgemeld_at, r.updated_at, r.created_at); }
function matches(r: Row, q: string) { const query = q.toLowerCase(); if (!query) return true; return [eventNaam(r), eventDatum(r), naam(r), sportschool(r), r.va_nummer, r.discipline, r.klasse, r.geslacht, r.gewicht, reden(r), bondteam(r), r.matchmaker_naam].map(x=>s(x).toLowerCase()).join(" | ").includes(query); }
async function loadRows(q: string) { const {data,error}=await supabase.from("afmeldingen").select("*").order("afgemeld_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false,nullsFirst:false}).limit(10000); if(error) throw new Error(error.message); return ((data??[]) as Row[]).filter(r=>matches(r,q)); }
function topMap(rows: Row[], keyFn: (r: Row) => string, limit = 10) { const m=new Map<string,number>(); rows.forEach(r=>{const k=keyFn(r)||"Onbekend"; m.set(k,(m.get(k)??0)+1);}); return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit); }
function fighterStats(rows: Row[]) { const m=new Map<string,Row[]>(); rows.forEach(r=>{const va=s(r.va_nummer)||`zonder-va-${r.id}`; m.set(va,[...(m.get(va)??[]),r]);}); return [...m.entries()].map(([va,list])=>{ const last=list[0]??{}; return {va, naam:naam(last), sportschool:sportschool(last), totaal:list.length, events:new Set(list.map(r=>`${fmtDate(eventDatum(r))}::${eventNaam(r)}`)).size, laatste:fmtDate(afgemeldAt(last)), risico:list.length>=3?"ROOD - veel afmeldingen":list.length>=2?"ORANJE - herhaling":"GROEN - normaal"}; }).sort((a,b)=>b.totaal-a.totaal); }
async function makeExcel(rows: Row[]) { const wb=new ExcelJS.Workbook(); wb.creator="FightSupport"; wb.created=new Date(); const f=fighterStats(rows);
  const ws=wb.addWorksheet("Analyse afmeldingen"); ws.columns=[{header:"VA",key:"va",width:14},{header:"Naam",key:"naam",width:28},{header:"Sportschool",key:"sportschool",width:26},{header:"Afmeldingen",key:"totaal",width:14},{header:"Evenementen",key:"events",width:14},{header:"Laatste",key:"laatste",width:16},{header:"Risico",key:"risico",width:24}]; f.forEach(x=>ws.addRow(x)); ws.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}}; ws.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FFFF4D00"}}; ws.autoFilter={from:"A1",to:"G1"}; ws.views=[{state:"frozen",ySplit:1}];
  const ev=wb.addWorksheet("Per evenement"); ev.columns=[{header:"Datum",key:"datum",width:16},{header:"Evenement",key:"event",width:32},{header:"Afmeldingen",key:"aantal",width:14},{header:"Unieke vechters",key:"vechters",width:16}]; topMap(rows,r=>`${fmtDate(eventDatum(r))}::${eventNaam(r)}`,1000).forEach(([k,aantal])=>{const [datum,event]=k.split("::"); ev.addRow({datum,event,aantal,vechters:new Set(rows.filter(r=>`${fmtDate(eventDatum(r))}::${eventNaam(r)}`===k).map(r=>s(r.va_nummer))).size});});
  const redenen=wb.addWorksheet("Redenen"); redenen.columns=[{header:"Reden",key:"reden",width:50},{header:"Aantal",key:"aantal",width:12}]; topMap(rows,reden,1000).forEach(([r,aantal])=>redenen.addRow({reden:r,aantal}));
  const raw=wb.addWorksheet("Alle afmeldingen"); raw.columns=[{header:"Afgemeld",key:"afgemeld",width:20},{header:"Datum",key:"datum",width:16},{header:"Evenement",key:"event",width:30},{header:"VA",key:"va",width:14},{header:"Naam",key:"naam",width:28},{header:"Sportschool",key:"sportschool",width:26},{header:"Bondteam",key:"bondteam",width:14},{header:"Klasse",key:"klasse",width:22},{header:"Gewicht",key:"gewicht",width:12},{header:"Reden",key:"reden",width:40}]; rows.forEach(r=>raw.addRow({afgemeld:fmtDateTime(afgemeldAt(r)),datum:fmtDate(eventDatum(r)),event:eventNaam(r),va:s(r.va_nummer),naam:naam(r),sportschool:sportschool(r),bondteam:bondteam(r),klasse:[r.discipline,r.klasse,r.geslacht].map(s).filter(Boolean).join(" / "),gewicht:s(r.gewicht),reden:reden(r)}));
  return Buffer.from(await wb.xlsx.writeBuffer()); }
function addLogo(doc: jsPDF) { try { const p=path.join(process.cwd(),"public","branding","fightsupport","fightsupport1.png"); if(fs.existsSync(p)) doc.addImage(fs.readFileSync(p).toString("base64"),"PNG",14,10,56,18); } catch{} }
function barChart(doc: jsPDF,title:string,data:[string,number][],x:number,y:number,w:number){ doc.setTextColor(255,255,255); doc.setFontSize(13); doc.text(title,x,y); const max=Math.max(1,...data.map(d=>d[1])); let yy=y+8; data.slice(0,8).forEach(([label,val])=>{const bw=(val/max)*(w-45); doc.setFillColor(255,77,0); doc.rect(x+42,yy-4,bw,5,"F"); doc.setTextColor(220,220,220); doc.setFontSize(8); doc.text(label.slice(0,22),x,yy); doc.text(String(val),x+44+bw,yy); yy+=8;}); }
function makePdf(rows: Row[]) { const doc=new jsPDF({unit:"mm",format:"a4"}); const f=fighterStats(rows); doc.setFillColor(5,5,5); doc.rect(0,0,210,297,"F"); addLogo(doc); doc.setTextColor(255,77,0); doc.setFontSize(20); doc.text("AFMELDINGEN ANALYSE",14,42); doc.setTextColor(220,220,220); doc.setFontSize(10); doc.text(`Gegenereerd: ${fmtDate(new Date())}`,14,49); const cards=[["Afmeldingen",rows.length],["Unieke vechters",f.length],["Veel herhaling",f.filter(x=>x.totaal>=3).length],["Evenementen",new Set(rows.map(r=>`${fmtDate(eventDatum(r))}::${eventNaam(r)}`)).size],["Sportscholen",new Set(rows.map(sportschool)).size]]; cards.forEach(([label,value],i)=>{const x=14+(i%3)*63; const y=62+Math.floor(i/3)*28; doc.setFillColor(18,18,18); doc.roundedRect(x,y,58,22,2,2,"F"); doc.setTextColor(170,170,170); doc.setFontSize(7); doc.text(String(label).toUpperCase(),x+4,y+7); doc.setTextColor(255,77,0); doc.setFontSize(17); doc.text(String(value),x+4,y+17);}); barChart(doc,"Top sportscholen",topMap(rows,sportschool,8),14,126,82); barChart(doc,"Top redenen",topMap(rows,reden,8),112,126,82); autoTable(doc,{startY:205,head:[["Risico","VA","Naam","Sportschool","Afmeldingen","Events","Laatste"]],body:f.slice(0,14).map(x=>[x.risico,x.va,x.naam,x.sportschool,x.totaal,x.events,x.laatste]),theme:"grid",styles:{fontSize:7,textColor:[20,20,20]},headStyles:{fillColor:[255,77,0],textColor:[255,255,255]}}); doc.addPage(); doc.setFillColor(5,5,5); doc.rect(0,0,210,297,"F"); addLogo(doc); doc.setTextColor(255,77,0); doc.setFontSize(16); doc.text("DETAILLIJST AFMELDINGEN",14,38); autoTable(doc,{startY:46,head:[["Afgemeld","Event","VA","Naam","Sportschool","Bondteam","Klasse","Gewicht","Reden"]],body:rows.map(r=>[fmtDateTime(afgemeldAt(r)),eventNaam(r),s(r.va_nummer),naam(r),sportschool(r),bondteam(r),[r.discipline,r.klasse].map(s).filter(Boolean).join(" / "),s(r.gewicht),reden(r)]),theme:"grid",styles:{fontSize:6,textColor:[20,20,20]},headStyles:{fillColor:[255,77,0],textColor:[255,255,255]}}); return Buffer.from(doc.output("arraybuffer")); }
export async function GET(req: NextRequest) { await requireAdmin(req); try { const url=new URL(req.url); const format=s(url.searchParams.get("format")||"xlsx").toLowerCase(); const q=s(url.searchParams.get("q")); const rows=await loadRows(q); if(format==="pdf") return new NextResponse(makePdf(rows),{headers:{"Content-Type":"application/pdf","Content-Disposition":"attachment; filename=\"fightsupport-afmeldingen-analyse.pdf\""}}); return new NextResponse(await makeExcel(rows),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=\"fightsupport-afmeldingen-analyse.xlsx\""}}); } catch(e:any) { return NextResponse.json({ok:false,error: "De aanvraag kon niet worden verwerkt."},{status:500}); } }
