"use client";

import { useParams, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { authedFetch } from "@/lib/api/authedFetch";

type R = Record<string, any>;
const t=(v:any,f="-")=>String(v??"").trim()||f;
const n=(v:any)=>String(v??"").trim().toLowerCase();
const okReview=(v:any)=>["approved","accepted","goedgekeurd","akkoord","resolved","afgehandeld","closed"].includes(n(v));
const date=(v:any)=>{if(!v)return "-";const d=new Date(String(v).length===10?`${v}T12:00:00`:v);return Number.isNaN(d.getTime())?t(v):d.toLocaleDateString("nl-NL")};
function sideData(row:R,ctx:R[]){const pn=Number(row?.partij_nr);const c=ctx.find(x=>Number(x?.partij_nr)===pn)||{};const s=row?.hoek==="blauw"?"blauw":"rood";return {partij:pn>0?`P${pn}`:t(row?.toernooi_code,"T"),naam:t(c?.[`${s}_naam_fp`]??c?.[`${s}_naam_mm`]??row?.fighter_name,"Onbekend"),gym:t(c?.[`${s}_gym_mm`]??c?.[`${s}_gym_fp`]??c?.[`${s}_sportschool`],"-")}}
export default function MatchmakerEindrapportPage(){
 const {matchmakingId}=useParams<{matchmakingId:string}>(); const router=useRouter(); const [data,setData]=useState<any>(); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const r=await authedFetch(`/api/rapport/matchmaker-eindrapport?matchmaking_id=${encodeURIComponent(matchmakingId)}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j?.ok)throw new Error(j?.error||"Eindrapport laden mislukt");setData(j)}catch(e:any){setError(e?.message||String(e))}})()},[matchmakingId]);
 const s=useMemo(()=>{if(!data)return null;const ctx:R[]=data.bout_context||[],res:R[]=data.resultaten||[],act:R[]=data.fighter_actueel||[];const open=res.filter(x=>!okReview(x.review_status)&&!["ok","info"].includes(n(x.resultaat)));const cat=(q:(x:R)=>boolean)=>open.filter(q).map(x=>({...sideData(x,ctx),raw:x}));const lic=cat(x=>String(x.rule_code||"").toUpperCase().includes("LICENT"));const nova=cat(x=>{const c=String(x.rule_code||"").toUpperCase();return c.includes("FIGHTPASPOORT")||c.includes("GEEN_FIGHTPASSPORT_INFO")});const start=cat(x=>String(x.rule_code||"").toUpperCase().includes("STARTVERBOD"));const keur=cat(x=>{const c=String(x.rule_code||"").toUpperCase();return c.includes("KEURMERK")||c.includes("SPORTSCHOOL_NIET_GEVONDEN")});const verb=cat(x=>n(x.resultaat)==="verbod"&&!String(x.rule_code||"").toUpperCase().includes("STARTVERBOD"));const disp=cat(x=>n(x.resultaat)==="dispensatie"||String(x.rule_code||"").toUpperCase().includes("DISPENSATIE"));const eind=(x:any)=>{const va=String(x.raw?.fighter_id??"").replace(/\D/g,"");const a=act.find(y=>String(y.va_nummer??"").replace(/\D/g,"")===va);return t(a?.keurmerk_einddatum??a?.keurmerk_einde,"")};return {ctx,lic,nova,start,keur,verb,disp,eind,akkoord:open.length===0};},[data]);
 if(error)return <main className="p-5 text-red-300">{error}</main>;if(!data||!s)return <main className="p-5 text-zinc-300">Eindrapport laden...</main>;
 const Pair=({title,a,b}:{title:string,a:any[],b:any[]})=><section className="grid gap-2 md:grid-cols-2">{[[title,a],[title==="Licentie"?"Geen VA / FightPassport":"Startverbod",b]].map(([h,list]:any)=><div key={h} className="overflow-hidden rounded border border-zinc-700 bg-[#151518]"><div className="flex justify-between bg-zinc-700 px-2 py-1 text-[11px] font-black uppercase"><span>{h}</span><span>{list.length}</span></div>{list.map((x:any,i:number)=><div key={i} className="grid grid-cols-[42px_1fr] gap-2 border-t border-zinc-800 px-2 py-1 text-[11px]"><b className="text-[#ff6a2a]">{x.partij}</b><span><b>{x.naam}</b>{x.gym!=="-"?` · ${x.gym}`:""}</span></div>)}</div>)}</section>;
 return <main className="min-h-screen bg-[#101012] p-3 text-white"><section className="mx-auto max-w-[1200px] overflow-hidden rounded-lg border border-zinc-700"><header className="flex items-center gap-3 bg-[#1b1b1f] px-4 py-2"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#ff4d00]">Matchmaker eindrapport</div><h1 className="text-lg font-black">{t(data.event?.naam)}</h1><div className="text-[11px] text-zinc-400">{date(data.event?.datum)} · {t(data.event?.locatie)} · {s.ctx.length} partijen</div></div><div className={`ml-auto rounded px-4 py-2 text-sm font-black ${s.akkoord?"bg-zinc-200 text-zinc-950":"bg-[#ff4d00] text-white"}`}>{s.akkoord?"EVENT AKKOORD":"EVENT GEBLOKKEERD"}</div><button onClick={()=>router.push(`/dashboard/matchmaker/matchmaking/${matchmakingId}`)} className="rounded border border-zinc-600 px-3 py-1 text-xs font-bold">Terug</button></header><div className="space-y-2 p-3"><Pair title="Licentie" a={s.lic} b={s.nova}/><section className="grid gap-2 md:grid-cols-2"><div className="overflow-hidden rounded border border-zinc-700 bg-[#151518]"><div className="flex justify-between bg-zinc-700 px-2 py-1 text-[11px] font-black uppercase"><span>Geen geldig keurmerk</span><span>{s.keur.length}</span></div>{s.keur.map((x:any,i:number)=><div key={i} className="px-2 py-1 text-[11px]"><b>{x.gym}</b>{s.eind(x)?` · einde ${date(s.eind(x))}`:""}</div>)}</div><div className="overflow-hidden rounded border border-zinc-700 bg-[#151518]"><div className="flex justify-between bg-zinc-700 px-2 py-1 text-[11px] font-black uppercase"><span>Startverbod</span><span>{s.start.length}</span></div>{s.start.map((x:any,i:number)=><div key={i} className="px-2 py-1 text-[11px]"><b>{x.naam}</b>{x.gym!=="-"?` · ${x.gym}`:""}</div>)}</div></section>{s.verb.length>0&&<section className="overflow-hidden rounded border border-[#ff4d00]"><div className="bg-[#ff4d00] px-2 py-1 text-xs font-black uppercase">Verboden partijen · {s.verb.length}</div>{s.verb.map((x:any,i:number)=><div key={i} className="grid grid-cols-[50px_1fr] gap-2 bg-zinc-100 px-2 py-1 text-[11px] text-zinc-950"><b>{x.partij}</b><span>{t(x.raw?.boodschap??x.raw?.rule??x.raw?.rule_code)}</span></div>)}</section>}{s.disp.length>0&&<section className="overflow-hidden rounded border border-[#ff4d00]"><div className="bg-[#ff4d00] px-2 py-1 text-xs font-black uppercase">Blokkerende dispensaties · {s.disp.length}</div>{s.disp.map((x:any,i:number)=><div key={i} className="grid grid-cols-[50px_1fr] gap-2 bg-zinc-100 px-2 py-1 text-[11px] text-zinc-950"><b>{x.partij}</b><span>{t(x.raw?.boodschap??x.raw?.rule??x.raw?.rule_code)}</span></div>)}</section>}</div></section></main>
}
