"use client";

import { useState } from "react";
import Link from "next/link";
import { Search, RefreshCw, UserPlus } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";

type Candidate = { va_nummer:string; naam?:string|null; leeftijd?:number|null; huidige_sportschool?:string|null; al_gekoppeld?:boolean };

async function token() { const { data } = await supabase.auth.getSession(); return data.session?.access_token ?? ""; }

export default function VechterToevoegenPage() {
  const [q,setQ]=useState(""); const [rows,setRows]=useState<Candidate[]>([]); const [busy,setBusy]=useState(false); const [adding,setAdding]=useState<string|null>(null); const [message,setMessage]=useState("");
  async function search(){ if(q.trim().length<2){setMessage("Vul minimaal 2 tekens of een VA-nummer in.");return;} setBusy(true);setMessage(""); try{ const t=await token(); const r=await fetch(`/api/sportscholen/vechters?q=${encodeURIComponent(q.trim())}`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}); const j=await r.json(); if(!r.ok) throw new Error(j.error||"Zoeken mislukt"); setRows(j.candidates||[]); if(!(j.candidates||[]).length)setMessage("Geen vechters gevonden."); }catch(e:any){setMessage(e.message||"Zoeken mislukt");}finally{setBusy(false);} }
  async function add(row:Candidate){ setAdding(row.va_nummer);setMessage(""); try{const t=await token();const r=await fetch("/api/sportscholen/vechters",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({va_nummer:row.va_nummer})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Toevoegen mislukt");setMessage(j.message||"Vechter toegevoegd.");setRows(x=>x.map(v=>v.va_nummer===row.va_nummer?{...v,al_gekoppeld:true}:v));}catch(e:any){setMessage(e.message||"Toevoegen mislukt");}finally{setAdding(null);} }
  return <main className="min-h-screen bg-[#090a0c] p-4 text-white"><section className="mx-auto max-w-5xl space-y-4"><div className="border border-white/20 bg-[#15171a] p-5"><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff4d00]">Sportschool</p><h1 className="mt-1 text-3xl font-black uppercase">Vechter uit database toevoegen</h1><p className="mt-2 text-sm text-zinc-300">Zoek een bestaande vechter op naam of VA-nummer. Alleen de gegevens die nodig zijn om de juiste vechter te herkennen worden getoond.</p><Link href="/dashboard/sportscholen" className="mt-4 inline-block border border-white/30 px-4 py-2 text-xs font-black uppercase !text-white">← Terug</Link></div><div className="flex gap-2 border border-white/20 bg-[#15171a] p-4"><div className="flex flex-1 items-center gap-2 border border-white/20 bg-black px-3"><Search size={18} className="text-[#ff4d00]"/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")search();}} placeholder="Naam of VA-nummer" className="w-full bg-transparent py-3 !text-white placeholder:!text-zinc-500 caret-white outline-none"/></div><button onClick={search} disabled={busy} className="border border-[#ff4d00] bg-[#ff4d00] px-5 text-xs font-black uppercase text-black disabled:opacity-50">{busy?<RefreshCw className="animate-spin" size={17}/>:"Zoeken"}</button></div>{message&&<div className="border border-[#ff4d00]/50 bg-[#241008] p-3 text-sm font-bold text-[#ffd2bd]">{message}</div>}<div className="overflow-hidden border border-white/20"><table className="w-full text-sm"><thead className="bg-black text-left text-xs uppercase"><tr><th className="p-3">Naam</th><th className="p-3">Leeftijd</th><th className="p-3">VA-nummer</th><th className="p-3">Huidige sportschool</th><th className="p-3 text-right">Actie</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.va_nummer} className={i%2?"bg-white text-black":"bg-[#15171a] text-white"}><td className="p-3 font-black">{r.naam||"-"}</td><td className="p-3">{r.leeftijd ?? "-"}</td><td className="p-3 font-mono font-black">{r.va_nummer}</td><td className="p-3">{r.huidige_sportschool||"-"}</td><td className="p-3 text-right"><button disabled={r.al_gekoppeld||adding===r.va_nummer} onClick={()=>add(r)} className="inline-flex items-center gap-2 border border-[#ff4d00] bg-[#ff4d00] px-3 py-2 text-xs font-black uppercase text-black disabled:border-zinc-500 disabled:bg-zinc-500"><UserPlus size={15}/>{r.al_gekoppeld?"Al gekoppeld":adding===r.va_nummer?"Bezig...":"Toevoegen"}</button></td></tr>)}</tbody></table></div></section></main>;
}
