// app/api/control-engine/matchmaker/full/start/route.ts
// Volledige Matchmaker-controle voor Upload en Eindcontrole. Eigen scraper + eigen Matchmaker libs.

import { NextResponse } from "next/server";
import { spawn } from "child_process";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";
import { buildControleBoutContext } from "@/lib/matchmaker/buildControleBoutContext";
import { enrichControleBoutContext } from "@/lib/matchmaker/enrichControleBoutContext";
import { rulesEngine } from "@/lib/matchmaker/rulesEngine";
import { assertCanAccessMatchmaking, requireUserWithRole } from "@/app/api/_utils/authz";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
const RUN_TYPE = "control-engine-matchmaker-total";
const FULL_SCRAPER_FILE = "scraper_fp_matchmaker_full.js";
const PROCESS_COUNT = 3;
const WORKERS_PER_PROCESS = 8;

type ReviewRow = { partij_nr?: number|null; bout_id?: string|null; rule_code?: string|null; hoek?: string|null; toernooi_code?: string|null; fighter_id?: string|null; toernooi_va_nummer?: string|null; review_status?: string|null; review_note?: string|null; reviewed_by?: string|null; reviewed_at?: string|null; aantekeningen?: string|null };
function toVaStrict(value: unknown) { const digits=String(value??"").replace(/\D/g,""); return /^\d{3,6}$/.test(digits)?digits:null; }
function pickVA(row:any,side:"rood"|"blauw") { const values=side==="rood"?[row?.va_rood,row?.rood_va,row?.rood_va_mm,row?.rood_va_nummer,row?.rood_fighter_id]:[row?.va_blauw,row?.blauw_va,row?.blauw_va_mm,row?.blauw_va_nummer,row?.blauw_fighter_id]; for(const value of values){const va=toVaStrict(value);if(va)return va;} return null; }
function clampInt(value:unknown,fallback:number,min:number,max:number){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.floor(n))):fallback;}
function roleAllowed(role:string|null|undefined){return ["matchmaker","admin","superadmin"].includes(String(role??"").toLowerCase());}
function resolveScriptPath(file:string){const root=process.cwd();const candidates=[path.join(root,"ControlEngine","scrapers","fp_bundle_matchmaker",file),path.join(root,"ControlEngine","ControlEngine","scrapers","fp_bundle_matchmaker",file),path.join(root,"control-engine","scrapers","fp_bundle_matchmaker",file),path.join(root,"control-engine","control-engine","scrapers","fp_bundle_matchmaker",file),path.join(root,"scrapers","fp_bundle_matchmaker",file)];const found=candidates.find(p=>fs.existsSync(p));if(!found)throw new Error(`Matchmaker full scraper niet gevonden: ${file}\n- ${candidates.join("\n- ")}`);return found;}
function runNodeScript(scriptPath:string,args:string[],envExtra:Record<string,string>,prefix:string){return new Promise<{ms:number}>((resolve,reject)=>{const started=Date.now();const child=spawn(process.execPath,[scriptPath,...args],{stdio:["ignore","pipe","pipe"],shell:false,cwd:path.dirname(scriptPath),windowsHide:true,env:{...process.env,...envExtra}});let stdout="",stderr="";child.stdout?.on("data",d=>{const t=d.toString();stdout+=t;process.stdout.write(`[${prefix}] ${t}`)});child.stderr?.on("data",d=>{const t=d.toString();stderr+=t;process.stderr.write(`[${prefix}] ${t}`)});child.on("error",reject);child.on("close",code=>code===0?resolve({ms:Date.now()-started}):reject(new Error(`Matchmaker scraper exit ${code}\n${stderr}\n${stdout}`)));});}
async function updateRun(id:string,patch:Record<string,unknown>){const{error}=await supabase.from("controle_runs").update(patch).eq("id",id);if(error)console.warn("[matchmaker/full] run update:",error.message);}
async function abortOwnRunning(matchmakingId:string){const{error}=await supabase.from("controle_runs").update({status:"aborted",afgerond_op:new Date().toISOString(),is_latest:false,foutmelding:"Afgebroken omdat een nieuwe volledige Matchmaker-controle is gestart."}).eq("matchmaking_id",matchmakingId).eq("run_type",RUN_TYPE).eq("status","running");if(error)throw error;}
async function createRun(matchmakingId:string,userId:string|null,role:string|null){const{data,error}=await supabase.from("controle_runs").insert({matchmaking_id:matchmakingId,gestart_door_user_id:userId,gestart_door_rol:role,status:"running",gestart_op:new Date().toISOString(),run_type:RUN_TYPE,is_latest:true,totaal_aantal:0,verwerkt_aantal:0,progress:0,current_step:"Volledige Matchmakercontrole wordt gestart..."}).select("id").single();if(error)throw error;if(!data?.id)throw new Error("Geen controle_run_id ontvangen.");await supabase.from("controle_runs").update({is_latest:false}).eq("matchmaking_id",matchmakingId).eq("run_type",RUN_TYPE).neq("id",data.id);return String(data.id);}
async function loadBouts(matchmakingId:string){const{data,error}=await supabase.from("matchmaking_bouts_raw").select("*").eq("matchmaking_id",matchmakingId).or("verwijderd.is.null,verwijderd.eq.false").order("partij_nr");if(error)throw error;return data??[];}
function reviewStatus(v:unknown):"approved"|"rejected"|null{const s=String(v??"").trim().toLowerCase();if(["approved","approve","goedgekeurd","ok"].includes(s))return"approved";if(["rejected","reject","afgekeurd","afkeur"].includes(s))return"rejected";return null;}
function reviewKey(row:ReviewRow,bout:boolean){return[String(row.partij_nr??""),bout?String(row.bout_id??""):"",String(row.rule_code??"").toLowerCase(),String(row.hoek??"").toLowerCase(),String(row.toernooi_code??"").toUpperCase(),String(row.fighter_id??"").replace(/\D/g,""),String(row.toernooi_va_nummer??"").replace(/\D/g,"")].join("|");}
async function previousReviews(matchmakingId:string):Promise<ReviewRow[]>{const{data,error}=await supabase.from("controle_resultaten").select("partij_nr,bout_id,rule_code,hoek,toernooi_code,fighter_id,toernooi_va_nummer,review_status,review_note,reviewed_by,reviewed_at,aantekeningen,created_at").eq("matchmaking_id",matchmakingId).not("review_status","is",null).order("reviewed_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(error)throw error;return(data??[]).filter((r:any)=>!!reviewStatus(r.review_status));}
async function carryReviews(matchmakingId:string,runId:string,previous:ReviewRow[]){if(!previous.length)return 0;const strict=new Map<string,ReviewRow>(),fallback=new Map<string,ReviewRow>();for(const r of previous){if(!strict.has(reviewKey(r,true)))strict.set(reviewKey(r,true),r);if(!fallback.has(reviewKey(r,false)))fallback.set(reviewKey(r,false),r);}const{data,error}=await supabase.from("controle_resultaten").select("id,partij_nr,bout_id,rule_code,hoek,toernooi_code,fighter_id,toernooi_va_nummer").eq("matchmaking_id",matchmakingId).eq("controle_run_id",runId);if(error)throw error;let count=0;for(const row of data??[]){const old=strict.get(reviewKey(row,true))??fallback.get(reviewKey(row,false));const status=old?reviewStatus(old.review_status):null;if(!old||!status)continue;const{error:e}=await supabase.from("controle_resultaten").update({review_status:old.review_status??null,review_note:old.review_note??null,reviewed_by:old.reviewed_by??null,reviewed_at:old.reviewed_at??null,aantekeningen:old.aantekeningen??null,resultaat:status==="approved"?"OK":"AFKEUR",actie_status:status==="approved"?"goedgekeurd":"afgekeurd"}).eq("id",(row as any).id);if(e)throw e;count++;}return count;}
async function runFullScrape(matchmakingId:string,runId:string,va:string[],opts:any){const script=resolveScriptPath(FULL_SCRAPER_FILE);const chunks=Array.from({length:PROCESS_COUNT},()=>[] as string[]);va.forEach((v,i)=>chunks[i%PROCESS_COUNT].push(v));const active=chunks.filter(x=>x.length);const batch=`matchmaker-${matchmakingId}-${crypto.randomUUID()}`;await Promise.all(active.map((chunk,i)=>{const nums=chunk.map(Number).filter(Number.isFinite),min=Math.min(...nums),max=Math.max(...nums);return runNodeScript(script,["1","1"],{FP_TOTAL_VA_LIST:chunk.join(","),FP_TOTAL_RUN_KIND:"retry",FP_TOTAL_RESULTS:"true",FP_TOTAL_WORKERS:String(WORKERS_PER_PROCESS),WORKERS:String(WORKERS_PER_PROCESS),FP_TOTAL_TIMEOUT_MS:String(opts.scrapeTimeoutMs),FP_TOTAL_LOGIN_RETRIES:"1",FP_TOTAL_TRANSIENT_RETRIES:"1",FP_SKIP_RUN_TERMINATOR:"true",FP_TOTAL_BATCH_ID:batch,FP_TOTAL_BATCH_PART:String(i+1),FP_TOTAL_BATCH_PARTS:String(active.length),FP_TOTAL_BATCH_START_VA:String(min),FP_TOTAL_BATCH_END_VA:String(max),FP_ADMIN_MATCHMAKING_ID:matchmakingId,FP_ADMIN_CONTROLE_RUN_ID:runId,STAGGER_MS:String(opts.staggerMs),TAB_ATTEMPTS:String(opts.tabAttempts),SOFT_WAIT_MS:String(opts.softWaitMs),BETWEEN_ATTEMPTS_MS:String(opts.betweenAttemptsMs),HEADLESS:process.env.HEADLESS??"false",PUPPETEER_HEADLESS:process.env.PUPPETEER_HEADLESS??process.env.HEADLESS??"false"},`fp_matchmaker_full_${i+1}`)}));return{batch,processes:active.length};}

export async function POST(req:Request){let matchmakingId:string|null=null,runId:string|null=null;try{const body=await req.json().catch(()=>({}));matchmakingId=String(body?.matchmaking_id??"").trim()||null;if(!matchmakingId)return NextResponse.json({error:"matchmaking_id ontbreekt."},{status:400});const{userId,role}=await requireUserWithRole(req);if(!roleAllowed(role))return NextResponse.json({error:"Geen toegang tot Matchmaker-controle."},{status:403});await assertCanAccessMatchmaking({matchmaking_id:matchmakingId,userId,role});const opts={staggerMs:clampInt(body?.stagger_ms??450,450,0,5000),tabAttempts:clampInt(body?.tab_attempts??5,5,1,30),softWaitMs:clampInt(body?.soft_wait_ms??200,200,0,5000),betweenAttemptsMs:clampInt(body?.between_attempts_ms??350,350,0,5000),scrapeTimeoutMs:clampInt(body?.scrape_timeout_ms??120000,120000,30000,300000)};await abortOwnRunning(matchmakingId);const reviews=await previousReviews(matchmakingId);runId=await createRun(matchmakingId,userId??null,role??null);const bouts=await loadBouts(matchmakingId);if(!bouts.length)throw new Error("Geen actieve partijen gevonden.");const set=new Set<string>();for(const b of bouts){const r=pickVA(b,"rood"),bl=pickVA(b,"blauw");if(r)set.add(r);if(bl)set.add(bl);}const va=[...set];if(!va.length)throw new Error("Geen geldige VA-nummers gevonden.");await updateRun(runId,{totaal_aantal:va.length,progress:12,current_step:`Volledige Matchmaker FightPassport-scrape: ${va.length} vechters (3 x 8 workers)...`});const scrape=await runFullScrape(matchmakingId,runId,va,opts);await updateRun(runId,{verwerkt_aantal:va.length,progress:74,current_step:"Matchmaker context opbouwen en verrijken..."});await buildControleBoutContext(matchmakingId,runId);await enrichControleBoutContext(matchmakingId,runId);const{data:ctx,error:ctxError}=await supabase.from("controle_bout_context").select("*").eq("matchmaking_id",matchmakingId).eq("controle_run_id",runId).order("partij_nr");if(ctxError)throw ctxError;if(!ctx?.length)throw new Error("Geen Matchmaker controle_bout_context opgebouwd.");await updateRun(runId,{progress:86,current_step:"Matchmaker rules-engine draait..."});const hits=await rulesEngine({matchmaking_id:matchmakingId,controle_run_id:runId,ctxRows:ctx});const carried=await carryReviews(matchmakingId,runId,reviews);
// Geen oude context/resultaten verwijderen: eerdere runs en besluiten zijn historie en 24u-referentie.
await updateRun(runId,{status:"klaar",afgerond_op:new Date().toISOString(),progress:100,verwerkt_aantal:va.length,current_step:carried?`Controle klaar. ${carried} eerdere beoordeling(en) behouden.`:"Controle klaar.",is_latest:true,foutmelding:null});return NextResponse.json({ok:true,matchmaking_id:matchmakingId,controle_run_id:runId,source:"matchmaker_total",scraper:{file:FULL_SCRAPER_FILE,va_count:va.length,processes:scrape.processes,workers_per_process:WORKERS_PER_PROCESS,batch_id:scrape.batch},context_rows:ctx.length,rules_hits:Array.isArray(hits)?hits.length:0,carried_reviews:carried});}catch(error:any){console.error("[control-engine/matchmaker/full/start]",error);if(runId)await updateRun(runId,{status:"failed",foutmelding:error?.message??String(error),afgerond_op:new Date().toISOString(),current_step:"Matchmakercontrole mislukt."});return NextResponse.json({ok:false,matchmaking_id:matchmakingId,controle_run_id:runId,error:error?.message??String(error)},{status:500});}}
