"use client";

import { authedFetch } from "@/lib/api/authedFetch";
import Link from "next/link";
import { use, useEffect, useState } from "react";
export default function VechterRapportPage({ params }: { params: Promise<{ vaNummer: string }> }) {
  const { vaNummer } = use(params); const [item, setItem] = useState<any>(null); const [error, setError] = useState("");
  useEffect(() => { authedFetch(`/api/admin/beheer/talentstatus/vechter/${vaNummer}`, { cache: "no-store" }).then(r => r.json()).then(j => j.ok ? setItem(j.item) : setError(j.error)); }, [vaNummer]);
  return <main className="min-h-screen bg-[#2b2b2b] p-6 text-white"><style>{`.talent-silver-btn, .talent-silver-btn *{color:#000!important;}`}</style><section className="mx-auto max-w-6xl border border-zinc-500 bg-[#121212] shadow-2xl"><header className="border-b border-zinc-600 bg-gradient-to-r from-[#1d1d1d] via-[#303030] to-[#151515] p-5"><Link href="/dashboard/admin/beheer/talentstatus/rapportage" className="talent-silver-btn border border-zinc-300 bg-gradient-to-b from-white via-zinc-200 to-zinc-500 px-3 py-1 text-xs font-black uppercase !text-black">Terug</Link><h1 className="mt-3 text-2xl font-black uppercase">Rapport per vechter</h1></header>{error && <p className="m-4 border border-red-500 bg-red-950 p-3">{error}</p>}{!item ? <p className="p-5">Laden...</p> : <div className="p-5"><h2 className="text-xl font-black text-[#ff4d00]">{item.naam}</h2><p className="text-sm text-zinc-300">VA {item.va_nummer} / {item.sportschool || "-"} / {item.land}</p><p className="mt-2 text-sm">Status: <b>{item.status}</b> | Talentstatus: <b>{item.talent_status}</b> | Partijen: <b>{item.partijen_totaal} / {item.max_proef_partijen}</b></p><div className="mt-5 overflow-x-auto"><table className="w-full border-collapse text-sm"><thead className="bg-[#252525] text-left text-xs uppercase text-zinc-300"><tr><th className="border border-zinc-700 p-2">Event</th><th className="border border-zinc-700 p-2">Vechters</th><th className="border border-zinc-700 p-2">Gewicht</th><th className="border border-zinc-700 p-2">Uitslag</th></tr></thead><tbody>{(item.partijen || []).map((p: any) => <tr key={p.id} className="bg-[#171717]"><td className="border border-zinc-800 p-2">{p.event_naam || "-"}<br/><span className="text-xs text-zinc-400">{p.event_datum || ""}</span></td><td className="border border-zinc-800 p-2">{p.vechter_naam} vs {p.tegenstander_naam}</td><td className="border border-zinc-800 p-2">{p.vechter_gewicht || "-"} / {p.tegenstander_gewicht || "-"}</td><td className="border border-zinc-800 p-2">{p.winnaar || "-"}<br/>{p.uitslag || ""}</td></tr>)}</tbody></table></div></div>}</section></main>;
}
