-- Centrale FightPassport mirror voor Fightsupport.
-- Bedoeld voor server-side service-role gebruik. RLS staat op alle tabellen aan;
-- er worden bewust geen brede client policies aangemaakt.

create table if not exists public.fightpassport_fighters (
  va_nummer text primary key,
  naam text,
  voornaam text,
  voorletters text,
  tussenvoegsel text,
  achternaam text,
  geboortedatum date,
  geslacht text,
  geboorteland text,
  nationaliteit text,
  email text,

  fit_to_fight boolean,
  licentie_actief boolean,
  heeft_startverbod boolean,

  totaal_wedstrijden integer,
  gewonnen integer,
  kos integer,

  nulmeting_gewicht numeric,
  nulmeting_discipline text,
  nulmeting_klasse text,
  nulmeting_totaal integer,
  nulmeting_gewonnen integer,
  nulmeting_verloren integer,
  nulmeting_onbeslist integer,
  nulmeting_kos integer,
  nulmeting_overige_ervaring boolean,
  nulmeting_opmerking text,

  berekende_klasse text,
  mma_level text,

  raw_summary jsonb not null default '{}'::jsonb,
  raw_details jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_scraped_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.fightpassport_results (
  id bigint generated by default as identity primary key,
  va_nummer text not null references public.fightpassport_fighters(va_nummer) on delete cascade,
  datum date,
  evenement text,
  tegenstander text,
  sportschool text,
  discipline text,
  klasse text,
  gewicht text,
  uitslag text,
  raw_json jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists fightpassport_results_dedupe_idx
on public.fightpassport_results (
  va_nummer,
  coalesce(datum, date '1900-01-01'),
  coalesce(evenement, ''),
  coalesce(tegenstander, ''),
  coalesce(discipline, ''),
  coalesce(klasse, ''),
  coalesce(uitslag, '')
);

create table if not exists public.fightpassport_fighter_gyms (
  id bigint generated by default as identity primary key,
  va_nummer text not null references public.fightpassport_fighters(va_nummer) on delete cascade,
  organisatie_naam text not null,
  plaats text,
  land text,
  organisatie_type text,
  raw_json jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists fightpassport_fighter_gyms_dedupe_idx
on public.fightpassport_fighter_gyms (va_nummer, organisatie_naam, coalesce(plaats, ''));

create table if not exists public.fightpassport_startbans (
  id bigint generated by default as identity primary key,
  va_nummer text not null references public.fightpassport_fighters(va_nummer) on delete cascade,
  soort text,
  ingang date,
  einde date,
  opgelegd_door text,
  reden text,
  evenement text,
  evenement_datum date,
  actief boolean,
  raw_json jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists fightpassport_startbans_dedupe_idx
on public.fightpassport_startbans (
  va_nummer,
  coalesce(ingang, date '1900-01-01'),
  coalesce(einde, date '1900-01-01'),
  coalesce(reden, ''),
  coalesce(evenement, '')
);

create table if not exists public.fightpassport_licenses (
  id bigint generated by default as identity primary key,
  va_nummer text not null references public.fightpassport_fighters(va_nummer) on delete cascade,
  soort text,
  status text,
  geldig_van date,
  geldig_tot date,
  bond text,
  raw_json jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists fightpassport_licenses_dedupe_idx
on public.fightpassport_licenses (
  va_nummer,
  coalesce(soort, ''),
  coalesce(geldig_van, date '1900-01-01'),
  coalesce(geldig_tot, date '1900-01-01')
);

create table if not exists public.fightpassport_sync_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null default 'full',
  start_va integer not null,
  end_va integer not null,
  last_processed_va integer,
  processed_count integer not null default 0,
  found_count integer not null default 0,
  licensed_count integer not null default 0,
  error_count integer not null default 0,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error_message text,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists fightpassport_fighters_license_idx on public.fightpassport_fighters (licentie_actief);
create index if not exists fightpassport_fighters_startban_idx on public.fightpassport_fighters (heeft_startverbod);
create index if not exists fightpassport_fighters_last_scraped_idx on public.fightpassport_fighters (last_scraped_at);
create index if not exists fightpassport_results_va_idx on public.fightpassport_results (va_nummer);
create index if not exists fightpassport_startbans_va_idx on public.fightpassport_startbans (va_nummer);

alter table public.fightpassport_fighters enable row level security;
alter table public.fightpassport_results enable row level security;
alter table public.fightpassport_fighter_gyms enable row level security;
alter table public.fightpassport_startbans enable row level security;
alter table public.fightpassport_licenses enable row level security;
alter table public.fightpassport_sync_runs enable row level security;

-- Geen anon/authenticated policies: browserclients krijgen dus geen directe toegang.
-- De scraper en serverroutes gebruiken SUPABASE_SERVICE_ROLE_KEY en omzeilen RLS veilig server-side.

comment on table public.fightpassport_fighters is 'Centrale actuele FightPassport mirror; geen matchmaking-run data.';
comment on column public.fightpassport_fighters.email is 'Login-e-mailadres uit het FightPassport detailvenster; uitsluitend server-side gebruiken.';
